### ISSUE TITLE
No code file!

### ISSUE THREAD

**Issue by DogmaF** [yayoyo66/SRStitcher#1]
Where's the code?

**Comment by yayoyo66** [comment]
Thank you for your interest in my work.

I've recently been working on a modification of my old solution (because I've found that there's room for improvement), so I'm refactoring the code and experimenting with parameters. Also, the manuscript I wrote before is quite rough and there are some mistakes in it, so I am also rewriting the manuscript.

These two things have taken up most of my working time now, which makes it hard to organize and upload source code. The source code is not expected to be available until next month and I will reply to you when I update the source code. 

Thanks for understanding.

**Comment by DogmaF** [comment]
I understand. Thanks for letting me know. And good luck with your project!

**Comment by yayoyo66** [comment]
The code is open source now, and the paper has been updated, a lot of changes made in the last version, any problems with the code can report to us, thank you
